### PR TITLE
Create Grambank_most_updated_sheet.tsv

### PR DESCRIPTION
**Pull request by HedvigS**
adding most updated sheet to this repos instead of glottobank/grambank

### CODE REVIEW

**Review by xrotwang — CHANGES_REQUESTED** [review]
Could we maybe put this sheet into a directory "docs" or similar? I think it's good if all/most of the files on top-level of a repository are self-explanatory and feel this isn't the case here.

**Comment by HedvigS** [comment]
Sure thing

**Comment by HedvigS** [comment]
How's something like this? Now I included the feature groupings, which has been requested by both by coders and people analysing the data.

**Comment by xrotwang** [comment]
I think we should already make this a bit more "publication-ready", e.g. 
- rename `Grambank_feature_groupings` to `feature_groupings`
- remove the `for_coding` and `for_analysis` directories and instead
- add a `feature_groupings/README.md`, linking to and explaining what each of the groupings is supposed to do

Ideally, the groupings would also follow a consistent scheme regarding column names.

**Comment by HedvigS** [comment]
Okay, sure!

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
