### PR TITLE
drop multistate features from data sheet template

### PR DESCRIPTION
**Pull request by johenglisch**
Dropping the multi-state features from the data sheet template to incentivise coders to fill out the binarised versions instead.

### CODE REVIEW

**Review by HedvigS — APPROVED** [review]

**Comment by HedvigS** [comment]
i've updated the wiki articles for all multistate features to include instructions for the binarised features.

**Comment by johenglisch** [comment]
I just noticed that the new description looks a bit odd in sheets where the multistate features don't exist anymore:

>This feature focuses on the order of cardinal numerals (not ordinal numerals)
>and nouns in quantified[...]
>This feature has also been split into two binary features, ""GB024a [...]

Maybe it would make things more clear if the description name-drops the multi-state feature, like e.g.:

>GB024 focuses on the order of cardinal numerals (not ordinal numerals)
>and nouns in quantified[...]
>This feature has also been split into two binary features, ""GB024a [...]

**Comment by HedvigS** [comment]
> I just noticed that the new description looks a bit odd in sheets where the multistate features don't exist anymore:
> 
> > This feature focuses on the order of cardinal numerals (not ordinal numerals)
> > and nouns in quantified[...]
> > This feature has also been split into two binary features, ""GB024a [...]
> 
> Maybe it would make things more clear if the description name-drops the multi-state feature, like e.g.:
> 
> > GB024 focuses on the order of cardinal numerals (not ordinal numerals)
> > and nouns in quantified[...]
> > This feature has also been split into two binary features, ""GB024a [...]

Hm.. yeah.. That's a good point! Let me see to that.

**Comment by HedvigS** [comment]
> > I just noticed that the new description looks a bit odd in sheets where the multistate features don't exist anymore:
> > > This feature focuses on the order of cardinal numerals (not ordinal numerals)
> > > and nouns in quantified[...]
> > > This feature has also been split into two binary features, ""GB024a [...]
> > 
> > 
> > Maybe it would make things more clear if the description name-drops the multi-state feature, like e.g.:
> > > GB024 focuses on the order of cardinal numerals (not ordinal numerals)
> > > and nouns in quantified[...]
> > > This feature has also been split into two binary features, ""GB024a [...]
> 
> Hm.. yeah.. That's a good point! Let me see to that.

@johenglisch Done :)!

**Pull request merged**
