### PR TITLE
Make template sheets for submissions

### PR DESCRIPTION
**Pull request by HedvigS**
I'd like to point users to two spreadsheets, one language-wise one feature-wise that they should use if they want to submit more than 10 datapoints for changing.

### CODE REVIEW

**Comment by xrotwang** [comment]
AFAICT the difference between the two sheets is that the language-wise sheet contains more columns (clarifying comments, etc), but they have the same 195 rows. How is one supposed to help with language-wise suggestions?

I also think, these sheets should be created from current wiki content - possibly with each release, and from a pygrambank command? Or is the wiki going to be frozen at some point?

**Comment by HedvigS** [comment]
> AFAICT the difference between the two sheets is that the language-wise sheet contains more columns (clarifying comments, etc), but they have the same 195 rows. How is one supposed to help with language-wise suggestions?

Yes, that's fair enough. I just thought it might help people conceptually if the were two different files, but we can have just one.
 
> I also think, these sheets should be created from current wiki content - possibly with each release, and from a pygrambank command?

So like how the most_udpated_sheet is created? We could just point them to that and add a "Language_ID" column?

> Or is the wiki going to be frozen at some point?
the wiki is not going to be frozen anytime soon.

**Comment by xrotwang** [comment]
Ah, pointing to the most updated sheet sounds like the perfect solution from my POV.

**Comment by HedvigS** [comment]
> Ah, pointing to the most updated sheet sounds like the perfect solution from my POV.

Sure, let's do that :)

Can that sheet also have a col for "Language_ID" in that case? It'd be useful for the feature-wise stuff.

**Comment by xrotwang** [comment]
That's a good task to get into pygrambank coding.

Hedvig Skirgård ***@***.***> schrieb am Mo., 14. Feb. 2022,
18:03:

**Comment by HedvigS** [comment]
> That's a good task to get into pygrambank coding. Hedvig Skirgård ***@***.***> schrieb am Mo., 14. Feb. 2022, 18:03:
> […](#)

haha okay. I'll see if I can figure out how to add that in pygrambank without breaking everything :)

**Pull request closed without merging**
