### PR TITLE
re-run new after pygrambank update

### PR DESCRIPTION
**Pull request by HedvigS**

### CODE REVIEW

**Comment by HedvigS** [comment]
I see that the check fails, but I cannot interpret why.

**Comment by HedvigS** [comment]
I guess it is because Langauge_ID is not a specified col in the cldf structure dataset json.

**Comment by xrotwang** [comment]
Is this still relevant? If so, you may want to remove `Language_ID` from the sheet again (i.e. reverse https://github.com/grambank/pygrambank/pull/59/files) and then run `grambank new`?

**Comment by HedvigS** [comment]
I think that it would be good yes if the blank sheet is updated. I think it should contain a Language_ID col and that the cldf structure dataset should include a Language_ID field.

**Comment by xrotwang** [comment]
The CLDF StructureDataset does contain a `Language_ID` column. But adding one to individual sheets seems problematic - or at least superfluous. If sheet name and Language_ID values contain glottocodes, do we have to make sure they match?

**Comment by HedvigS** [comment]
> The CLDF StructureDataset does contain a `Language_ID` column. But adding one to individual sheets seems problematic - or at least superfluous. If sheet name and Language_ID values contain glottocodes, do we have to make sure they match?

The reason to add a Language_ID col to the blank coding sheet is to make the suggestion workflow easier. If outsiders can access it and use it to submit suggestions re multiple languages, that will make that workflow easier.

In cases of regular coding, coders can entirely ignore the Language_ID column, just as they can ignore other columns that aren't Value, Comment and Source. You are right, they only need to make sure the glottocode is right in the fn.

**Review by xrotwang — APPROVED** [review]

**Comment by HedvigS** [comment]
Thank you!

**Pull request merged**
