### PR TITLE
Release v1.0

### PR DESCRIPTION
**Pull request by johenglisch**
Release candidate

 * Copied over cldf generation code
 * Recipe fixes
 * Automated cldf validation and ci
 * `metadata.json`, `.zenodo.json`, `README.md`
 * The metadata columns in the parameter table had invalid column names, so I fixed that (shouldn't really affect anything).
 * Generated data

### CODE REVIEW

**Comment by HedvigS** [comment]
Thank you @johenglisch .

I believe that @RustyGray will want us to also list the release paper as necessary for citing the database, which currently would mean: 

https://github.com/grambank/grambank-analysed/blob/main/R_grambank/wrangle_authors/grambank-entry.bib

**Review by xrotwang — APPROVED** [review]

**Comment by johenglisch** [comment]
So, as far as I'm concerned this should be good to go.

Do you see anything that's left to do here, @HedvigS?

**Review by HedvigS — APPROVED** [review]

**Comment by HedvigS** [comment]
Looks good!!

**Comment by HedvigS** [comment]
The only thing I'd really worry about is the values table being the same as what's used in the manuscript, but that seems all double and triple checked now right :)?

**Comment by xrotwang** [comment]
```
$ git remote -v
origin	https://github.com/glottobank/grambank-cldf (fetch)
origin	https://github.com/glottobank/grambank-cldf (push)

$ git status 
HEAD detached at v1.0.1

no changes added to commit (use "git add" and/or "git commit -a")
$ csvstat -y 0 -c Value cldf/values.csv 
  4. "Value"

	Type of data:          Text
	Contains null values:  False
	Unique values:         5
	Longest value:         1, characters
	Most common values:    0 (242782x)
	                       1 (112315x)
	                       ? (79638x)
	                       2 (5410x)
	                       3 (1518x)

Row count: 441663
```
vs.
```
$ git remote -v
origin	https://github.com/grambank/grambank (fetch)
origin	https://github.com/grambank/grambank (push)
$ git status 
On branch release-v1.0
Your branch is up to date with 'origin/release-v1.0'.

nothing added to commit but untracked files present (use "git add" to track)
$ csvstat -y 0 -c Value cldf/values.csv 
  4. "Value"

	Type of data:          Text
	Contains null values:  False
	Unique values:         5
	Longest value:         1, characters
	Most common values:    0 (242782x)
	                       1 (112315x)
	                       ? (79638x)
	                       2 (5410x)
	                       3 (1518x)

Row count: 441663
```

**Comment by RustyGray** [comment]
Yes, absolutely. R.

**Comment by HedvigS** [comment]
Okay. I think we're ready to go! Thanks @xrotwang for confirming the value table diff and @RustyGray for confirming the citation set-up.

**Comment by johenglisch** [comment]
Voilá: https://doi.org/10.5281/zenodo.7740140

**Comment by xrotwang** [comment]
looks good!

**Comment by HedvigS** [comment]
> Voilá: https://doi.org/10.5281/zenodo.7740140

EXCELLENT. Copy-pasting into manuscript now.

**Pull request merged**
