### PR TITLE
Update feature_grouping_for_analysis.csv

### PR DESCRIPTION
**Pull request by HedvigS**
add information for binarised multi state features

### CODE REVIEW

**Review by xrotwang — COMMENTED** [review]
Does it make sense to have `GB024a` - i.e. something that's **not** a feature ID - as value of the `Feature_ID` column?

**Comment by HedvigS** [comment]
For analysis, we often use the binarised features, and those are the valid names for those. I can think of another workflow if you don't lke it.

**Review by xrotwang — APPROVED** [review]
ok, fine with me.

**Comment by HedvigS** [comment]
Thanks.

**Pull request merged**
