### PR TITLE
datapoints -> Datapoints

### PR DESCRIPTION
**Pull request by HedvigS**

### CODE REVIEW

**Comment by xrotwang** [comment]
This sheet is created by code in `pygrambank`, so to make this change stick, one would need to fix it here, too: https://github.com/grambank/pygrambank/blob/b8d1a1c2a4db0b01e22187ad2fe757670ee3f1a4/src/pygrambank/commands/new.py#L35

**Comment by HedvigS** [comment]
Ah, right.

**Comment by HedvigS** [comment]
Before doing that, perhaps we should just confirm with @SimonGreenhill that this was indeed his preference? Lest my memory fails me.

**Comment by xrotwang** [comment]
I don't really care - and `pygrambank` doesn't either:
https://github.com/grambank/pygrambank/blob/b8d1a1c2a4db0b01e22187ad2fe757670ee3f1a4/src/pygrambank/sheet.py#L38-L40
:)

**Comment by HedvigS** [comment]
fair enough, that's what I thought. Someone just DMed me saying this seemed inconsitent. I suspected it doesn't matter for pygrambank either.

**Comment by HedvigS** [comment]
maybe just to avoid further possible messages about the discrepancy we could just change it. would that be ok?

**Comment by SimonGreenhill** [comment]
yeah, consistency is good. Especially if it's confusing people

**Comment by xrotwang** [comment]
Sure, go aheas. Just make sure the changes are either done in both places, or done in `pygrambank`, and the sheet here recreated with `grambank new`.

**Comment by HedvigS** [comment]
On it.

I tried to do it simply by using the web interface before but I couldn't because I can't create branches in the master repos so I'm now forking and doing a PR that way.

**Pull request closed without merging**
